import { Step } from 'react-joyride';

export const TUTORIAL_STEPS: Step[] = [
  {
    target: 'body',
    content: "Welcome to Time Master! Let's get you set up for success.",
    title: 'Welcome',
    placement: 'center',
    disableBeacon: true,
    disableOverlayClose: true,
    hideCloseButton: true,
    hideFooter: false,
    spotlightClicks: false,
    data: { }
  },
  {
    target: '#nav-workplan-tab',
    content: "First, let's plan your week. Tap here to go to the Workplan.",
    title: 'Plan Navigation',
    placement: 'top',
    disableBeacon: true,
    disableOverlayClose: true,
    hideCloseButton: true,
    hideFooter: true,
    spotlightClicks: true,
    data: { action: 'nav-workplan' }
  },
  {
    target: '[data-tutorial="create-workplan-btn"]',
    content: "Tap here to create a new workplan.",
    title: 'Create Workplan',
    placement: 'bottom',
    disableBeacon: true,
    disableOverlayClose: true,
    hideCloseButton: true,
    hideFooter: true,
    spotlightClicks: true,
    data: { action: 'click-create-workplan' }
  },
  {
    target: '[data-tutorial="workplan-list-item"]',
    content: "Select your newly created workplan.",
    title: 'Select Workplan',
    placement: 'bottom',
    disableBeacon: true,
    disableOverlayClose: true,
    hideCloseButton: true,
    hideFooter: true,
    spotlightClicks: true,
    data: { action: 'select-workplan' }
  },
  {
    target: '[data-tutorial="add-workplan-task"]',
    content: "Now add a task to your workplan.",
    title: 'Add Task',
    placement: 'bottom',
    disableBeacon: true,
    disableOverlayClose: true,
    hideCloseButton: true,
    hideFooter: true,
    spotlightClicks: true,
    data: { action: 'click-add-task' }
  },
  {
    target: '[data-tutorial="workplan-item"]',
    content: "Your task has been added. You can see it here.",
    title: 'Task Added',
    placement: 'top',
    disableBeacon: true,
    disableOverlayClose: true,
    hideCloseButton: true,
    hideFooter: false,
    spotlightClicks: false,
    data: { }
  },
  {
    target: '#today-nav',
    content: "Now let's focus on today. Tap here to go to the Today view.",
    title: 'Today Navigation',
    placement: 'top',
    disableBeacon: true,
    disableOverlayClose: true,
    hideCloseButton: true,
    hideFooter: true,
    spotlightClicks: true,
    data: { action: 'nav-today' }
  },
  {
    target: '[data-tutorial="today-goal-card"]',
    content: "Set a main goal for today to keep you focused.",
    title: 'Set Goal',
    placement: 'bottom',
    disableBeacon: true,
    disableOverlayClose: true,
    hideCloseButton: true,
    hideFooter: true,
    spotlightClicks: true,
    data: { action: 'click-set-goal' }
  },
  {
    target: '[data-tutorial="add-today-task"]',
    content: "Add specific tasks you want to accomplish today.",
    title: 'Add Today Task',
    placement: 'bottom',
    disableBeacon: true,
    disableOverlayClose: true,
    hideCloseButton: true,
    hideFooter: true,
    spotlightClicks: true,
    data: { action: 'click-add-today-task' }
  },
  {
    target: '[data-tutorial="start-task-button"]',
    content: "Tap the play button on a task to get ready.",
    title: 'Select Task',
    placement: 'bottom',
    disableBeacon: true,
    disableOverlayClose: true,
    hideCloseButton: true,
    hideFooter: true,
    spotlightClicks: true,
    data: { action: 'click-start-task-today' }
  },
  {
    target: '[data-tutorial="start-timer-btn"]',
    content: "Confirm your settings and start the timer.",
    title: 'Start Timer',
    placement: 'bottom',
    disableBeacon: true,
    disableOverlayClose: true,
    hideCloseButton: true,
    hideFooter: true,
    spotlightClicks: true,
    data: { action: 'click-start-timer-setup' }
  },
  {
    target: '[data-tutorial="timer-pause-button"]',
    content: "You can pause the timer if you need a break.",
    title: 'Pause Task',
    placement: 'top',
    disableBeacon: true,
    disableOverlayClose: true,
    hideCloseButton: true,
    hideFooter: true,
    spotlightClicks: true,
    data: { action: 'click-pause-timer' }
  },
  {
    target: '[data-tutorial="timer-stop-button"]',
    content: "When you're done, tap stop to log your time.",
    title: 'Stop Task',
    placement: 'bottom',
    disableBeacon: true,
    disableOverlayClose: true,
    hideCloseButton: true,
    hideFooter: true,
    spotlightClicks: true,
    data: { action: 'click-stop-timer' }
  },
  {
    target: '#nav-reports',
    content: "Check your progress and see how you're spending your time.",
    title: 'Reports',
    placement: 'top',
    disableBeacon: true,
    disableOverlayClose: true,
    hideCloseButton: true,
    hideFooter: true,
    spotlightClicks: true,
    data: { action: 'nav-reports' }
  },
  {
    target: 'body',
    content: "You're all set! Start mastering your time now.",
    title: 'Success',
    placement: 'center',
    disableBeacon: true,
    disableOverlayClose: true,
    hideCloseButton: true,
    hideFooter: false,
    spotlightClicks: false,
    data: { }
  }
];
